### PR TITLE
silence fallback warnings

### LINKED ISSUE #139: Disable warnings for fallback to root locale
### vue & vue-i18n version
2.2.6, 6.0.0

### Steps to reproduce
Use the example for [component locales](https://kazupon.github.io/vue-i18n/en/component.html)

### What is Expected?
No warning in developer console

### What is actually happening?
```
[vue-i18n] Value of key 'message.greeting' is not a string!
[vue-i18n] Fall back to translate the keypath 'message.greeting' with root locale.
```

My use case for component locales is as follows:
* Commonly used words are global locales (firstname, lastname, ...)
* Each page in my SPA ships with its own component locales (benefits from code splitting: only load locales for the current page)
* The page component uses both global and component locales

Right now I get warnings whenever I use a global locale. They go away when compiling for production, but it is still annoying as it interrupts the development process. Can you please provide a way to disable these warnings?

### PR DESCRIPTION
**Pull request by SzNagyMisu**
aims to fix #139 

warnings should be silenced for fallback but not if there is no translation at all.

PR is incomplete as yet, but still have some questions.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -230,7 +236,7 @@ export default class VueI18n {
       if (isPlainObject(message)) {
         ret = message[key]
         if (typeof ret !== 'string') {
-          if (process.env.NODE_ENV !== 'production' && !this._silentTranslationWarn) {
+          if (process.env.NODE_ENV !== 'production' && !this._silentTranslationWarn && !(this._silentFallbackWarn && (this._isFallbackRoot() || locale !== this.fallbackLocale))) {
```
[the remark this answers is not in the document]
Comment (kazupon) [reply src/index.js]: > is it ok to check `locale !== this.fallbackLocale`? 

Yes, that's right!

>I got confused because `_translate` gets `fallback` as a param, but it always points to `this.fallbackLocale`.

The current vue-i18n is very complexity due to none of your business. 😭 In next major version, I will to write with full-scratch.

[the remark this answers is not in the document]
Comment (kazupon) [reply src/index.js]: > Also, we have a similar condition in line 246/252.

Just as you said, these is similar condition.
In unit test coverage (the following is  removed `/* istanbul ignore else */`), the code of 246/249 is not passed in unit tests. 

image


However, `t` or `$t` is returned the value of `TranslateResult`

https://github.com/kazupon/vue-i18n/blob/e8790244408d812728c95253b63b637a734d1c32/types/index.d.ts#L12

If you want to add a test case, we will be very helpful if you do so.
Although it is a bad design as API 😂, We need to maintain backwards compatibility.

In next major version, I'll plan to change this specification.

File: vuepress/api/README.md [hunk 2]
```diff
@@ -259,6 +259,17 @@ Whether suppress warnings outputted when localization fails.
 
 If `true`, suppress localization fail warnings.
 
+#### silentFallbackWarn
+
+> 8.8+
```
Comment (kazupon) [inline vuepress/api/README.md]:
```suggestion
> :new: 8.8+
```

File: test/unit/silent.test.js [hunk 3]
```diff
@@ -78,37 +78,84 @@ describe('silent', () => {
...
+    describe('if first try is not null, undefined, array, plain object or string,', () => {
+      it('should suppress `not a string` warnings for fallback to fallbackLocale.', () => {
+        const vm = new Vue({
+          i18n: new VueI18n({
+            locale: 'hu',
+            fallbackLocale: 'en',
+            silentFallbackWarn: true,
+            messages: {
+              en: { winner: 'winner' },
+              hu: { winner: true } // translation value is boolean
```
Comment (SzNagyMisu) [inline test/unit/silent.test.js]: @kazupon is it the right use case? `boolean`, `number` etc?

Comment (kazupon) [reply test/unit/silent.test.js]: > is it the right use case?
yes! that's correct! `not a string` is warning!

**Comment by kazupon** [comment]
@SzNagyMisu Thanks!

**Comment by meelie** [comment]
Thank you so much for this feature <3 !

**Comment by jbnv** [comment]
Question: How do we silence warning messages when there is no translation at all? I'm using Vue-I18n in an application framework where we probably will never actually need to translate to languages other than English, but Vue-I18n is very useful for loading configuration information. I'm finding that in a lot of cases it's less code to just write `$t('Some text here')` without defining a translation. But that results in a lot of unneeded warning messages.

**Comment by SzNagyMisu** [comment]
@jbnv 
I would recommend considering the constructor option [silentTranslationWarn](https://kazupon.github.io/vue-i18n/api/#silenttranslationwarn) or [missing](https://kazupon.github.io/vue-i18n/api/#missing).
There might be other options better tailored to your need, so having a look at each [constructor option](https://kazupon.github.io/vue-i18n/api/#constructor-options) might lead you to something I missed.

**Comment by jbnv** [comment]
That helps. Thanks.
